Repository SAITARUN55/Portfolio, pull requests merged in 2020-09, with the labels that each got.

#16 :bugs: Minor fixes
  _layouts/home.html
Labels: bug

#13 Update videos.yml
  _data/videos.yml
  assets/videos/dsa-interview-prep-series-e3.jpeg
Labels: content-update

#18 [A11y] Added titles for cards
  _layouts/home.html
  blog.html
  videos.html
Labels: enhancement
